server:
error:
  include-message: always
  include-binding-errors: always
auth:
  jwt:
    secret: 30faa058f27f690c7e9a098d54ebcfb3d8725bcb85ee7907a2d84c69622229e2
  endpoints:
    protected: /hello, /calc/sum, /calc/subtract
spring:
  datasource:
    #71742509 -- 70325f11fe5973d8af2245672c9fe5240dabaae3673dd777fba0b86bdf5770a3
    password: 70325f11fe5973d8af2245672c9fe5240dabaae3673dd777fba0b86bdf5770a3
    #jdbc:postgresql://localhost:5433/onbalance -- jdbc:postgres://pacgxchvakxxdd:70325f11fe5973d8af2245672c9fe5240dabaae3673dd777fba0b86bdf5770a3@ec2-3-229-11-55.compute-1.amazonaws.com:5432/dcmcap4dcghv0s
    url: jdbc:postgres://pacgxchvakxxdd:70325f11fe5973d8af2245672c9fe5240dabaae3673dd777fba0b86bdf5770a3@ec2-3-229-11-55.compute-1.amazonaws.com:5432/dcmcap4dcghv0s
    #postgres -- pacgxchvakxxdd
    username: pacgxchvakxxdd
  jpa:
    hibernate:
      #create-drop -- validate
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
        show-sql: true